#!/usr/bin/env python
import sys
import dendropy
from dendropy.calculate import treecompare

distances=[]

# establish common taxon namespace
tns = dendropy.TaxonNamespace()
# ensure all trees loaded use common namespace
tree1 = dendropy.Tree.get(path="tree1.tree",schema='newick',taxon_namespace=tns)
filenames = sys.argv[1:]
for i in sys.argv[1:]:

	tree = dendropy.Tree.get(path=i,schema='newick',taxon_namespace=tns)



# tree_yielder = dendropy.Tree.yield_from_files(
#         files=files,
#         schema='newick',
#         taxon_namespace=tns)

# for tree_idx, tree in enumerate(tree_yielder):
	distances.append(treecompare.symmetric_difference(tree1, tree))
print distances
