#!/usr/bin/env python
import sys
import re
import dendropy
from dendropy.calculate import treecompare

distances=[]

# establish common taxon namespace
tns = dendropy.TaxonNamespace()
# ensure all trees loaded use common namespace
#reftree = dendropy.Tree.get(path="s001.align.1.msl.tree",schema='newick',taxon_namespace=tns)

reference_tree=True
for i in sys.argv[1:]:
    j = open(i,'r')

    for line in j:
        #print line
        match = re.search('<newick>(.+|\n)</newick>', line)
        if match and reference_tree==False:
            pretree= match.group(1)
        elif match and reference_tree==True:
            refpretree=match.group(1)
            reftree = dendropy.Tree.get(data=refpretree,schema='newick',taxon_namespace=tns)
            reference_tree=False #from now on we dont need another reference tree
    j.close()
#get() will automatically make data control as schema must be newick
tree = dendropy.Tree.get(data=pretree,schema='newick',taxon_namespace=tns)

distances.append(treecompare.symmetric_difference(reftree, tree))
print distances
